name: Generate Keystore Tool

on:
  workflow_dispatch: # This lets you run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate debug.keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore-file
          path: debug.keystore
